project:
  type: book
  output-dir: docs/
  pre-render: R/source.R

toc: true
number-sections: true

book:
  repo-url: https://github.com/johnmbf/dissertacao
  title: "A constituição em processo de judicialização"
  subtitle: "Um estudo da multidimensionalidade da judicialização da política a partir da análise das arguições de descumprimento de preceito fundamental"
  sidebar: 
    style: docked
  author: 
    - name: "Jonathan Morais Barcellos Ferreira"
      email: jonathanmbferreira@outlook.com
      affiliation:
        - name: Universidade Federal do Rio Grande
          departament: Faculdade de Direito
          city: Rio Grande
          state: Rio Grande do Sul
          country: Brasil
  date: 2025-06-15
  page-footer: 
    left: "Jonathan Morais Barcellos Ferreira (2025)"
    right: 
      - icon: instagram
        href: https://instagram.com/jo_mbf
  chapters: 
    - index.qmd
    - 01_introducao.qmd
    - 02_metodologia.qmd
    - 03_revisao.qmd
    - 04_adpfs.qmd
  appendices: 
    - code.qmd

execute:
  warning: false
  error: false
  cache: true
fig-align: center
fig-dpi: 600
df-print: paged
citation-location: document
citations-hover: true
footnotes-hover: true
reference-location: document
crossrefs-hover: true
license: "CC BY-NC"


crossref: 
  title-delim: "-"
  fig-title: "Figura"
  tbl-title: "Tabela"
  eq-title: "Equação"
  fig-prefix: "Figura"
  tbl-prefix: "Tabela"
  eq-prefix: "Equação"
  lst-title: "Código"
  lst-prefix: "Código"

lightbox: true

format: 
  html:
    cap-location: top
    code-copy: hover
    theme: cosmo
    page-layout: full
    
code-annotations: hover

lang: pt-br