---
title: "processos"
format: html
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6
)
knitr::opts_knit$set(
  root.dir = "../"
)
```

```{r}
processos <- readRDS("DATA/processos.rds")
```

Numero de ADPFs ajuizadas: `r processos |> dplyr::select(classe, numero) |> dplyr::distinct() |> dplyr::filter(classe == "ADPF") |> nrow()`. 

## Ramo do Direito

Ramo do direito por ADPF:

```{r}
processos |>
  dplyr::select(classe, numero, ramo_do_direito) |>
  dplyr::filter(classe == "ADPF") |>
  dplyr::distinct() |>
  tidyr::drop_na() |>
  dplyr::group_by(ramo_do_direito) |>
  dplyr::summarise(n = dplyr::n()) |> 
  dplyr::slice_max(n, n = 10) |>
  ggplot(aes(y = reorder(ramo_do_direito, n), x = n)) +
  geom_col(fill = "#5B96A5") +
  scale_x_continuous(expand = c(0,0), limits = c(0,900)) +
  labs(x = "Número de processos", y = "Ramo do Direito") +
  decJ::theme_decJ(x_num = TRUE)

decJ::save_decJ("PLOT/ramo_do_direito_adpf.png", l = 24)

processos |>
  dplyr::select(classe, numero, assunto_relacionado) |>
  dplyr::filter(classe == "ADPF") |>
  dplyr::distinct() |>
  tidyr::drop_na() |>
  dplyr::group_by(assunto_relacionado) |>
  dplyr::summarise(n = dplyr::n()) |> 
  dplyr::slice_max(n, n = 10) |>
  ggplot(aes(y = reorder(assunto_relacionado, n), x = n)) +
  geom_col(fill = "#5B96A5") +
  scale_x_continuous(expand = c(0,0), limits = c(0,900)) +
  labs(x = "Número de processos", y = "Assunto") +
  decJ::theme_decJ(x_num = TRUE)

decJ::save_decJ("PLOT/assunto_adpf.png", l = 24)
```

## Relatores

```{r}
processos |>
  dplyr::select(classe, numero, relator_atual) |>
  dplyr::filter(classe == "ADPF") |>
  dplyr::distinct() |>
  tidyr::drop_na() |>
  dplyr::group_by(relator_atual) |>
  dplyr::summarise(n = dplyr::n()) |>
  dplyr::arrange(desc(n)) |>
  knitr::kable(col.names = c("Relator", "Número"))
```

```{r}
processos |>
  dplyr::select(classe, numero, relator_atual) |>
  dplyr::filter(classe == "ADPF") |>
  dplyr::distinct() |>
  tidyr::drop_na() |>
  dplyr::group_by(relator_atual) |>
  dplyr::summarise(n = dplyr::n()) |>
  dplyr::arrange(desc(n)) |>
  ggplot(aes(x = 0, y = n)) +
  geom_boxplot(width = 1) +
  geom_jitter(width = 0.05) +
  labs (y = NULL) +
  decJ::theme_decJ(y_num = TRUE) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )

decJ::save_decJ("PLOT/relator_boxplot.png", a = 24, l = 16)
```

## Tempo de resposta

### Modelo Nulo

### Modelo Relator

### Modelo Legitimado

### Modelo Rito 12